"""Adding extra field to class book 

Revision ID: 05232a3fc58c
Revises: 6dcdad3202b0
Create Date: 2025-08-07 15:12:11.366299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05232a3fc58c'
down_revision: Union[str, Sequence[str], None] = '6dcdad3202b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
