"""add class metadata to sessions

Revision ID: 0b99f4e05605
Revises: 8d5a23116b96
Create Date: 2025-08-06 20:59:22.669959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b99f4e05605'
down_revision: Union[str, Sequence[str], None] = '8d5a23116b96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('title', sa.String(), nullable=True))
    op.add_column('sessions', sa.Column('day_of_week', sa.Integer(), nullable=True))
    op.add_column('sessions', sa.Column('is_class', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'is_class')
    op.drop_column('sessions', 'day_of_week')
    op.drop_column('sessions', 'title')
    # ### end Alembic commands ###
