"""add stripe_session_id to session_signups

Revision ID: 6dcdad3202b0
Revises: 5186e2d3b787
Create Date: 2025-08-07 12:30:59.399669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dcdad3202b0'
down_revision: Union[str, Sequence[str], None] = '5186e2d3b787'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_signups', sa.Column('stripe_session_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_signups', 'stripe_session_id')
    # ### end Alembic commands ###
