"""add stripe_checkout_url to session_signups

Revision ID: fd0b9f7996c4
Revises: 05232a3fc58c
Create Date: 2025-08-08 12:23:19.623254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd0b9f7996c4'
down_revision: Union[str, Sequence[str], None] = '05232a3fc58c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_signups', sa.Column('stripe_checkout_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_signups', 'stripe_checkout_url')
    # ### end Alembic commands ###
